---
eos_cli: |
  ip extcommunity-list regexp ECL-TYPE2-RT permit RT:10011:10011
  !
  route-map RM-FROM-OVERLAY-PEERS deny 10
    match extcommunity ECL-TYPE2-RT
  route-map RM-FROM-OVERLAY-PEERS permit 20
  !
  router bgp 65102
    address-family evpn
      neighbor EVPN-OVERLAY-PEERS route-map RM-FROM-OVERLAY-PEERS in