---
eos_cli: |
  ip community-list CL-RT5-REDISTRIBUTE permit 1:1
  ip prefix-list PL-RT5-HOST permit 0.0.0.0/0 le 32
  !
  route-map RM-TO-OVERLAY-CORE deny 10
    match community CL-RT5-REDISTRIBUTE
  route-map RM-TO-OVERLAY-CORE permit 20
  !
  router bgp 65102
    address-family evpn
      neighbor EVPN-OVERLAY-CORE route-map RM-TO-OVERLAY-CORE out