---
eos_cli: |
  ip extcommunity-list regexp ECL-TYPE2-RT permit RT:1[0-9][0-9][0-9][0-9]:1[0-9][0-9][0-9][0-9]
  !
  route-map RM-TO-OVERLAY-CORE permit 10
    match route-type local
  route-map RM-TO-OVERLAY-CORE permit 20
    match extcommunity ECL-TYPE2-RT
  !
  route-map RM-FROM-OVERLAY-PEERS permit 10
    set community no-advertise
  !
  router bgp 65202
    address-family evpn
      neighbor EVPN-OVERLAY-PEERS route-map RM-FROM-OVERLAY-PEERS in