---
eos_cli: |
  alias test1 ping 10.10.10.11 repeat 1000000 interval 2
  alias test2 ping 10.10.12.1 repeat 1000000 interval 2
  !
  interface Vlan10
    ip address 10.10.10.21/24
  interface Vlan12
    ip address 10.10.12.21/24
